Feature: Complete items in list
  I want to make sure that items can be completed in the TODO list at https://todomvc.com/examples/angular2/.

  Scenario Outline: Can complete items of the TODO list
    Given that I navigated to the todo list page using "<browser>"
    And the list has become available
    And that the list has the items: "<all-items-in-list>"
    When I click to complete the items: "<items-to-complete>"
    Then I should see the items "<completed-items>" completed and the items "<incomplete-items>" still incomplete

  @smoke
  Examples:
    | browser                    | all-items-in-list                                                                                                                                                           | items-to-complete                                                         | completed-items                                                                                                                                                               | incomplete-items                                                                                  |
    | Microsoft Edge             | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application | Create cucumber application capable of testing this page;Test application | Create cucumber application capable of testing this page;Test application                                                                                                     | Write application's documentation;Write test cases;Validate test cases;Submit testing application |
    | Google Chrome              | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application | Create cucumber application capable of testing this page;Test application | Create cucumber application capable of testing this page;Test application                                                                                                     | Write application's documentation;Write test cases;Validate test cases;Submit testing application |

  @regression
  Examples:
    | browser                    | all-items-in-list                                                                                                                                                           | items-to-complete                                                         | completed-items                                                                                                                                                               | incomplete-items                                                                                  |
    | Microsoft Edge             | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application | Create cucumber application capable of testing this page;Test application | Create cucumber application capable of testing this page;Test application                                                                                                     | Write application's documentation;Write test cases;Validate test cases;Submit testing application |
    | Microsoft Edge             | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application | Write test cases                                                          | Create cucumber application capable of testing this page;Test application;Write test cases                                                                                    | Write application's documentation;Validate test cases;Submit testing application                  |
    | Microsoft Edge             | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application | Write application's documentation;Validate test cases                     | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases                              | Submit testing application                                                                        |
    | Microsoft Edge             | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application | Submit testing application                                                | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application   |                                                                                                   |
    | Microsoft Edge - InPrivate | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application | Create cucumber application capable of testing this page;Test application | Create cucumber application capable of testing this page;Test application                                                                                                     | Write application's documentation;Write test cases;Validate test cases;Submit testing application |
    | Google Chrome              | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application | Create cucumber application capable of testing this page;Test application | Create cucumber application capable of testing this page;Test application                                                                                                     | Write application's documentation;Write test cases;Validate test cases;Submit testing application |
    | Google Chrome              | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application | Write test cases                                                          | Create cucumber application capable of testing this page;Test application;Write test cases                                                                                    | Write application's documentation;Validate test cases;Submit testing application                  |
    | Google Chrome              | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application | Write application's documentation;Validate test cases                     | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases                              | Submit testing application                                                                        |
    | Google Chrome              | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application | Submit testing application                                                | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application   |                                                                                                   |
    | Google Chrome - Incognito  | Create cucumber application capable of testing this page;Test application;Write application's documentation;Write test cases;Validate test cases;Submit testing application | Create cucumber application capable of testing this page;Test application | Create cucumber application capable of testing this page;Test application                                                                                                     | Write application's documentation;Write test cases;Validate test cases;Submit testing application |
